/*
 2010-2011 Benjamin Arthur Lupton <contact@balupton.com>
 @license New BSD License <http://creativecommons.org/licenses/BSD/>
 2010-2011 Benjamin Arthur Lupton <contact@balupton.com>
 @license New BSD License <http://creativecommons.org/licenses/BSD/>
 2010-2011 Benjamin Arthur Lupton <contact@balupton.com>
 @license New BSD License <http://creativecommons.org/licenses/BSD/>
 Public Domain
 @author Benjamin Arthur Lupton <contact@balupton.com>
 @author James Padolsey <https://gist.github.com/527683>
 Public Domain
 @author Benjamin Arthur Lupton <contact@balupton.com>
*/
"object"!==typeof JSON&&(JSON={});
(function(){function d(b){return 10>b?"0"+b:b}function p(c){b.lastIndex=0;return b.test(c)?'"'+c.replace(b,function(b){var c=n[b];return"string"===typeof c?c:"\\u"+("0000"+b.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+c+'"'}function h(b,d){var g,a,e,n,s=c,r,f=d[b];f&&"object"===typeof f&&"function"===typeof f.toJSON&&(f=f.toJSON(b));"function"===typeof k&&(f=k.call(d,b,f));switch(typeof f){case "string":return p(f);case "number":return isFinite(f)?String(f):"null";case "boolean":case "null":return String(f);
case "object":if(!f)return"null";c+=l;r=[];if("[object Array]"===Object.prototype.toString.apply(f)){n=f.length;for(g=0;g<n;g+=1)r[g]=h(g,f)||"null";e=0===r.length?"[]":c?"[\n"+c+r.join(",\n"+c)+"\n"+s+"]":"["+r.join(",")+"]";c=s;return e}if(k&&"object"===typeof k)for(n=k.length,g=0;g<n;g+=1)"string"===typeof k[g]&&(a=k[g],(e=h(a,f))&&r.push(p(a)+(c?": ":":")+e));else for(a in f)Object.prototype.hasOwnProperty.call(f,a)&&(e=h(a,f))&&r.push(p(a)+(c?": ":":")+e);e=0===r.length?"{}":c?"{\n"+c+r.join(",\n"+
c)+"\n"+s+"}":"{"+r.join(",")+"}";c=s;return e}}"function"!==typeof Date.prototype.toJSON&&(Date.prototype.toJSON=function(b){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+d(this.getUTCMonth()+1)+"-"+d(this.getUTCDate())+"T"+d(this.getUTCHours())+":"+d(this.getUTCMinutes())+":"+d(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(b){return this.valueOf()});var e=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
b=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,c,l,n={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},k;"function"!==typeof JSON.stringify&&(JSON.stringify=function(b,d,g){var a;l=c="";if("number"===typeof g)for(a=0;a<g;a+=1)l+=" ";else"string"===typeof g&&(l=g);if((k=d)&&"function"!==typeof d&&("object"!==typeof d||"number"!==typeof d.length))throw Error("JSON.stringify");return h("",{"":b})});
"function"!==typeof JSON.parse&&(JSON.parse=function(b,c){function d(a,b){var l,e,f=a[b];if(f&&"object"===typeof f)for(l in f)Object.prototype.hasOwnProperty.call(f,l)&&(e=d(f,l),void 0!==e?f[l]=e:delete f[l]);return c.call(a,b,f)}var a;b=String(b);e.lastIndex=0;e.test(b)&&(b=b.replace(e,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(b.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,
"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return a=eval("("+b+")"),"function"===typeof c?d({"":a},""):a;throw new SyntaxError("JSON.parse");})})();
(function(d,p){var h=d.History=d.History||{},e=d.jQuery;if("undefined"!==typeof h.Adapter)throw Error("History.js Adapter has already been loaded...");h.Adapter={bind:function(b,c,d){e(b).bind(c,d)},trigger:function(b,c,d){e(b).trigger(c,d)},extractEventData:function(b,c,d){return c&&c.originalEvent&&c.originalEvent[b]||d&&d[b]||p},onDomLoad:function(b){e(b)}};"undefined"!==typeof h.init&&h.init()})(window);
(function(d,p){var h=d.document,e=d.setInterval||e,b=d.History=d.History||{};if("undefined"!==typeof b.initHtml4)throw Error("History.js HTML4 Support has already been loaded...");b.initHtml4=function(){if("undefined"!==typeof b.initHtml4.initialized)return!1;b.initHtml4.initialized=!0;b.enabled=!0;b.savedHashes=[];b.isLastHash=function(c){var d=b.getHashByIndex();return c===d};b.isHashEqual=function(b,d){b=encodeURIComponent(b).replace(/%25/g,"%");d=encodeURIComponent(d).replace(/%25/g,"%");return b===
d};b.saveHash=function(c){if(b.isLastHash(c))return!1;b.savedHashes.push(c);return!0};b.getHashByIndex=function(c){var d=null;return d="undefined"===typeof c?b.savedHashes[b.savedHashes.length-1]:0>c?b.savedHashes[b.savedHashes.length+c]:b.savedHashes[c]};b.discardedHashes={};b.discardedStates={};b.discardState=function(c,d,e){var k=b.getHashByState(c);b.discardedStates[k]={discardedState:c,backState:e,forwardState:d};return!0};b.discardHash=function(c,d,e){b.discardedHashes[c]={discardedHash:c,backState:e,
forwardState:d};return!0};b.discardedState=function(c){c=b.getHashByState(c);return b.discardedStates[c]||!1};b.discardedHash=function(c){return b.discardedHashes[c]||!1};b.recycleState=function(c){var d=b.getHashByState(c);b.discardedState(c)&&delete b.discardedStates[d];return!0};b.emulated.hashChange&&(b.hashChangeInit=function(){b.checkerFunction=null;var c="",l,n,k,m=Boolean(b.getHash());b.isInternetExplorer()?(l=h.createElement("iframe"),l.setAttribute("id","historyjs-iframe"),l.setAttribute("src",
"#"),l.style.display="none",h.body.appendChild(l),l.contentWindow.document.open(),l.contentWindow.document.close(),n="",k=!1,b.checkerFunction=function(){if(k)return!1;k=!0;var e=b.getHash(),g=b.getHash(l.contentWindow.document);e!==c?(c=e,g!==e&&(n=e,l.contentWindow.document.open(),l.contentWindow.document.close(),l.contentWindow.document.location.hash=b.escapeHash(e)),b.Adapter.trigger(d,"hashchange")):g!==n&&(n=g,m&&""===g?b.back():b.setHash(g,!1));k=!1;return!0}):b.checkerFunction=function(){var e=
b.getHash()||"";e!==c&&(c=e,b.Adapter.trigger(d,"hashchange"));return!0};b.intervalList.push(e(b.checkerFunction,b.options.hashChangeInterval));return!0},b.Adapter.onDomLoad(b.hashChangeInit));b.emulated.pushState&&(b.onHashChange=function(c){c=c&&c.newURL||b.getLocationHref();var e=b.getHashByUrl(c);c=null;if(b.isLastHash(e))return b.busy(!1),!1;b.doubleCheckComplete();b.saveHash(e);if(e&&b.isTraditionalAnchor(e))return b.Adapter.trigger(d,"anchorchange"),b.busy(!1),!1;c=b.extractState(b.getFullUrl(e||
b.getLocationHref()),!0);if(b.isLastSavedState(c))return b.busy(!1),!1;b.getHashByState(c);if(e=b.discardedState(c))return b.getHashByIndex(-2)===b.getHashByState(e.forwardState)?b.back(!1):b.forward(!1),!1;b.pushState(c.data,c.title,encodeURI(c.url),!1);return!0},b.Adapter.bind(d,"hashchange",b.onHashChange),b.pushState=function(c,e,n,k){n=encodeURI(n).replace(/%25/g,"%");if(b.getHashByUrl(n))throw Error("History.js does not support states with fragment-identifiers (hashes/anchors).");if(!1!==k&&
b.busy())return b.pushQueue({scope:b,callback:b.pushState,args:arguments,queue:k}),!1;b.busy(!0);var m=b.createStateObject(c,e,n),h=b.getHashByState(m),g=b.getState(!1),g=b.getHashByState(g),a=b.getHash(),p=b.expectedStateId==m.id;b.storeState(m);b.expectedStateId=m.id;b.recycleState(m);b.setTitle(m);if(h===g)return b.busy(!1),!1;b.saveState(m);p||b.Adapter.trigger(d,"statechange");b.isHashEqual(h,a)||b.isHashEqual(h,b.getShortUrl(b.getLocationHref()))||b.setHash(h,!1);b.busy(!1);return!0},b.replaceState=
function(c,e,h,k){h=encodeURI(h).replace(/%25/g,"%");if(b.getHashByUrl(h))throw Error("History.js does not support states with fragment-identifiers (hashes/anchors).");if(!1!==k&&b.busy())return b.pushQueue({scope:b,callback:b.replaceState,args:arguments,queue:k}),!1;b.busy(!0);var m=b.createStateObject(c,e,h),q=b.getHashByState(m),g=b.getState(!1),a=b.getHashByState(g),p=b.getStateByIndex(-2);b.discardState(g,m,p);q===a?(b.storeState(m),b.expectedStateId=m.id,b.recycleState(m),b.setTitle(m),b.saveState(m),
b.Adapter.trigger(d,"statechange"),b.busy(!1)):b.pushState(m.data,m.title,m.url,!1);return!0});if(b.emulated.pushState&&b.getHash()&&!b.emulated.hashChange)b.Adapter.onDomLoad(function(){b.Adapter.trigger(d,"hashchange")})};"undefined"!==typeof b.init&&b.init()})(window);
(function(d,p){var h=d.console||p,e=d.document,b=d.navigator,c=!1,l=d.setTimeout,n=d.clearTimeout,k=d.setInterval,m=d.clearInterval,q=d.JSON,g=d.alert,a=d.History=d.History||{},t=d.history;try{c=d.sessionStorage,c.setItem("TEST","1"),c.removeItem("TEST")}catch(u){c=!1}q.stringify=q.stringify||q.encode;q.parse=q.parse||q.decode;if("undefined"!==typeof a.init)throw Error("History.js Core has already been loaded...");a.init=function(b){if("undefined"===typeof a.Adapter)return!1;"undefined"!==typeof a.initCore&&
a.initCore();"undefined"!==typeof a.initHtml4&&a.initHtml4();return!0};a.initCore=function(s){if("undefined"!==typeof a.initCore.initialized)return!1;a.initCore.initialized=!0;a.options=a.options||{};a.options.hashChangeInterval=a.options.hashChangeInterval||100;a.options.safariPollInterval=a.options.safariPollInterval||500;a.options.doubleCheckInterval=a.options.doubleCheckInterval||500;a.options.disableSuid=a.options.disableSuid||!1;a.options.storeInterval=a.options.storeInterval||1E3;a.options.busyDelay=
a.options.busyDelay||250;a.options.debug=a.options.debug||!1;a.options.initialTitle=a.options.initialTitle||e.title;a.options.html4Mode=a.options.html4Mode||!1;a.options.delayInit=a.options.delayInit||!1;a.intervalList=[];a.clearAllIntervals=function(){var f,b=a.intervalList;if("undefined"!==typeof b&&null!==b){for(f=0;f<b.length;f++)m(b[f]);a.intervalList=null}};a.debug=function(){a.options.debug&&a.log.apply(a,arguments)};a.log=function(){var a=!("undefined"===typeof h||"undefined"===typeof h.log||
"undefined"===typeof h.log.apply),b=e.getElementById("log"),c,d,l,k;a?(d=Array.prototype.slice.call(arguments),c=d.shift(),"undefined"!==typeof h.debug?h.debug.apply(h,[c,d]):h.log.apply(h,[c,d])):c="\n"+arguments[0]+"\n";d=1;for(l=arguments.length;d<l;++d){k=arguments[d];if("object"===typeof k&&"undefined"!==typeof q)try{k=q.stringify(k)}catch(m){}c+="\n"+k+"\n"}b?(b.value+=c+"\n-----\n",b.scrollTop=b.scrollHeight-b.clientHeight):a||g(c);return!0};a.getInternetExplorerMajorVersion=function(){var f=
a.getInternetExplorerMajorVersion,b;if("undefined"!==typeof a.getInternetExplorerMajorVersion.cached)b=a.getInternetExplorerMajorVersion.cached;else{b=3;for(var c=e.createElement("div"),d=c.getElementsByTagName("i");(c.innerHTML="\x3c!--[if gt IE "+ ++b+"]><i></i><![endif]--\x3e")&&d[0];);b=4<b?b:!1}return f.cached=b};a.isInternetExplorer=function(){return a.isInternetExplorer.cached="undefined"!==typeof a.isInternetExplorer.cached?a.isInternetExplorer.cached:Boolean(a.getInternetExplorerMajorVersion())};
a.emulated=a.options.html4Mode?{pushState:!0,hashChange:!0}:{pushState:!Boolean(d.history&&d.history.pushState&&d.history.replaceState&&!(/ Mobile\/([1-7][a-z]|(8([abcde]|f(1[0-8]))))/i.test(b.userAgent)||/AppleWebKit\/5([0-2]|3[0-2])/i.test(b.userAgent))),hashChange:Boolean(!("onhashchange"in d||"onhashchange"in e)||a.isInternetExplorer()&&8>a.getInternetExplorerMajorVersion())};a.enabled=!a.emulated.pushState;a.bugs={setHash:Boolean(!a.emulated.pushState&&"Apple Computer, Inc."===b.vendor&&/AppleWebKit\/5([0-2]|3[0-3])/.test(b.userAgent)),
safariPoll:Boolean(!a.emulated.pushState&&"Apple Computer, Inc."===b.vendor&&/AppleWebKit\/5([0-2]|3[0-3])/.test(b.userAgent)),ieDoubleCheck:Boolean(a.isInternetExplorer()&&8>a.getInternetExplorerMajorVersion()),hashEscape:Boolean(a.isInternetExplorer()&&7>a.getInternetExplorerMajorVersion())};a.isEmptyObject=function(a){for(var b in a)if(a.hasOwnProperty(b))return!1;return!0};a.cloneObject=function(a){a?(a=q.stringify(a),a=q.parse(a)):a={};return a};a.getRootUrl=function(){var a=e.location.protocol+
"//"+(e.location.hostname||e.location.host);e.location.port&&(a+=":"+e.location.port);return a+"/"};a.getBaseHref=function(){var a=e.getElementsByTagName("base"),b=null,b="";1===a.length&&(b=a[0],b=b.href.replace(/[^\/]+$/,""));(b=b.replace(/\/+$/,""))&&(b+="/");return b};a.getBaseUrl=function(){return a.getBaseHref()||a.getBasePageUrl()||a.getRootUrl()};a.getPageUrl=function(){return((a.getState(!1,!1)||{}).url||a.getLocationHref()).replace(/\/+$/,"").replace(/[^\/]+$/,function(a,b,c){return/\./.test(a)?
a:a+"/"})};a.getBasePageUrl=function(){return a.getLocationHref().replace(/[#\?].*/,"").replace(/[^\/]+$/,function(a,b,c){return/[^\/]$/.test(a)?"":a}).replace(/\/+$/,"")+"/"};a.getFullUrl=function(f,b){var c=f,d=f.substring(0,1);b="undefined"===typeof b?!0:b;/[a-z]+\:\/\//.test(f)||(c="/"===d?a.getRootUrl()+f.replace(/^\/+/,""):"#"===d?a.getPageUrl().replace(/#.*/,"")+f:"?"===d?a.getPageUrl().replace(/[\?#].*/,"")+f:b?a.getBaseUrl()+f.replace(/^(\.\/)+/,""):a.getBasePageUrl()+f.replace(/^(\.\/)+/,
""));return c.replace(/\#$/,"")};a.getShortUrl=function(f){var b=a.getBaseUrl(),c=a.getRootUrl();a.emulated.pushState&&(f=f.replace(b,""));f=f.replace(c,"/");a.isTraditionalAnchor(f)&&(f="./"+f);return f=f.replace(/^(\.\/)+/g,"./").replace(/\#$/,"")};a.getLocationHref=function(a){a=a||e;return a.URL===a.location.href?a.location.href:a.location.href===decodeURIComponent(a.URL)?a.URL:a.location.hash&&decodeURIComponent(a.location.href.replace(/^[^#]+/,""))===a.location.hash||-1==a.URL.indexOf("#")&&
-1!=a.location.href.indexOf("#")?a.location.href:a.URL||a.location.href};a.store={};a.idToState=a.idToState||{};a.stateToId=a.stateToId||{};a.urlToId=a.urlToId||{};a.storedStates=a.storedStates||[];a.savedStates=a.savedStates||[];a.normalizeStore=function(){a.store.idToState=a.store.idToState||{};a.store.urlToId=a.store.urlToId||{};a.store.stateToId=a.store.stateToId||{}};a.getState=function(b,c){"undefined"===typeof b&&(b=!0);"undefined"===typeof c&&(c=!0);var d=a.getLastSavedState();!d&&c&&(d=a.createStateObject());
b&&(d=a.cloneObject(d),d.url=d.cleanUrl||d.url);return d};a.getIdByState=function(b){var c=a.extractId(b.url),d;if(!c)if(d=a.getStateString(b),"undefined"!==typeof a.stateToId[d])c=a.stateToId[d];else if("undefined"!==typeof a.store.stateToId[d])c=a.store.stateToId[d];else{for(;c=(new Date).getTime()+String(Math.random()).replace(/\D/g,""),"undefined"!==typeof a.idToState[c]||"undefined"!==typeof a.store.idToState[c];);a.stateToId[d]=c;a.idToState[c]=b}return c};a.normalizeState=function(b){var c;
b&&"object"===typeof b||(b={});if("undefined"!==typeof b.normalized)return b;b.data&&"object"===typeof b.data||(b.data={});c={normalized:!0};c.title=b.title||"";c.url=a.getFullUrl(b.url?b.url:a.getLocationHref());c.hash=a.getShortUrl(c.url);c.data=a.cloneObject(b.data);c.id=a.getIdByState(c);c.cleanUrl=c.url.replace(/\??\&_suid.*/,"");c.url=c.cleanUrl;b=!a.isEmptyObject(c.data);(c.title||b)&&!0!==a.options.disableSuid&&(c.hash=a.getShortUrl(c.url).replace(/\??\&_suid.*/,""),/\?/.test(c.hash)||(c.hash+=
"?"),c.hash+="&_suid="+c.id);c.hashedUrl=a.getFullUrl(c.hash);(a.emulated.pushState||a.bugs.safariPoll)&&a.hasUrlDuplicate(c)&&(c.url=c.hashedUrl);return c};a.createStateObject=function(b,c,d){b={data:b,title:c,url:d};return b=a.normalizeState(b)};a.getStateById=function(b){b=String(b);return a.idToState[b]||a.store.idToState[b]||p};a.getStateString=function(b){b={data:a.normalizeState(b).data,title:b.title,url:b.url};return q.stringify(b)};a.getStateId=function(b){return a.normalizeState(b).id};
a.getHashByState=function(b){return a.normalizeState(b).hash};a.extractId=function(a){a=-1!=a.indexOf("#")?a.split("#")[0]:a;return((a=/(.*)\&_suid=([0-9]+)$/.exec(a))?String(a[2]||""):"")||!1};a.isTraditionalAnchor=function(a){return!/[\/\?\.]/.test(a)};a.extractState=function(b,c){var d=null,e,g;c=c||!1;(e=a.extractId(b))&&(d=a.getStateById(e));d||(g=a.getFullUrl(b),(e=a.getIdByUrl(g)||!1)&&(d=a.getStateById(e)),d||!c||a.isTraditionalAnchor(b)||(d=a.createStateObject(null,null,g)));return d};a.getIdByUrl=
function(b){return a.urlToId[b]||a.store.urlToId[b]||p};a.getLastSavedState=function(){return a.savedStates[a.savedStates.length-1]||p};a.getLastStoredState=function(){return a.storedStates[a.storedStates.length-1]||p};a.hasUrlDuplicate=function(b){var c=!1;return c=(c=a.extractState(b.url))&&c.id!==b.id};a.storeState=function(b){a.urlToId[b.url]=b.id;a.storedStates.push(a.cloneObject(b));return b};a.isLastSavedState=function(b){var c=!1;a.savedStates.length&&(b=b.id,c=a.getLastSavedState(),c=c.id,
c=b===c);return c};a.saveState=function(b){if(a.isLastSavedState(b))return!1;a.savedStates.push(a.cloneObject(b));return!0};a.getStateByIndex=function(b){var c=null;return c="undefined"===typeof b?a.savedStates[a.savedStates.length-1]:0>b?a.savedStates[a.savedStates.length+b]:a.savedStates[b]};a.getCurrentIndex=function(){var b=null;return b=1>a.savedStates.length?0:a.savedStates.length-1};a.getHash=function(b){b=a.getLocationHref(b);return a.getHashByUrl(b)};a.unescapeHash=function(b){b=a.normalizeHash(b);
return b=decodeURIComponent(b)};a.normalizeHash=function(a){return a.replace(/[^#]*#/,"").replace(/#.*/,"")};a.setHash=function(b,c){var d;if(!1!==c&&a.busy())return a.pushQueue({scope:a,callback:a.setHash,args:arguments,queue:c}),!1;a.busy(!0);(d=a.extractState(b,!0))&&!a.emulated.pushState?a.pushState(d.data,d.title,d.url,!1):a.getHash()!==b&&(a.bugs.setHash?(d=a.getPageUrl(),a.pushState(null,null,d+"#"+b,!1)):e.location.hash=b);return a};a.escapeHash=function(b){b=a.normalizeHash(b);b=d.encodeURIComponent(b);
a.bugs.hashEscape||(b=b.replace(/\%21/g,"!").replace(/\%26/g,"&").replace(/\%3D/g,"=").replace(/\%3F/g,"?"));return b};a.getHashByUrl=function(b){b=String(b).replace(/([^#]*)#?([^#]*)#?(.*)/,"$2");return b=a.unescapeHash(b)};a.setTitle=function(b){var c=b.title,d;c||(d=a.getStateByIndex(0))&&d.url===b.url&&(c=d.title||a.options.initialTitle);try{e.getElementsByTagName("title")[0].innerHTML=c.replace("<","&lt;").replace(">","&gt;").replace(" & "," &amp; ")}catch(g){}e.title=c;return a};a.queues=[];
a.busy=function(b){"undefined"!==typeof b?a.busy.flag=b:"undefined"===typeof a.busy.flag&&(a.busy.flag=!1);if(!a.busy.flag){n(a.busy.timeout);var c=function(){var b,d;if(!a.busy.flag)for(b=a.queues.length-1;0<=b;--b)d=a.queues[b],0!==d.length&&(d=d.shift(),a.fireQueueItem(d),a.busy.timeout=l(c,a.options.busyDelay))};a.busy.timeout=l(c,a.options.busyDelay)}return a.busy.flag};a.busy.flag=!1;a.fireQueueItem=function(b){return b.callback.apply(b.scope||a,b.args||[])};a.pushQueue=function(b){a.queues[b.queue||
0]=a.queues[b.queue||0]||[];a.queues[b.queue||0].push(b);return a};a.queue=function(b,c){"function"===typeof b&&(b={callback:b});"undefined"!==typeof c&&(b.queue=c);a.busy()?a.pushQueue(b):a.fireQueueItem(b);return a};a.clearQueue=function(){a.busy.flag=!1;a.queues=[];return a};a.stateChanged=!1;a.doubleChecker=!1;a.doubleCheckComplete=function(){a.stateChanged=!0;a.doubleCheckClear();return a};a.doubleCheckClear=function(){a.doubleChecker&&(n(a.doubleChecker),a.doubleChecker=!1);return a};a.doubleCheck=
function(b){a.stateChanged=!1;a.doubleCheckClear();a.bugs.ieDoubleCheck&&(a.doubleChecker=l(function(){a.doubleCheckClear();a.stateChanged||b();return!0},a.options.doubleCheckInterval));return a};a.safariStatePoll=function(){var b=a.extractState(a.getLocationHref());if(!a.isLastSavedState(b))return b||a.createStateObject(),a.Adapter.trigger(d,"popstate"),a};a.back=function(b){if(!1!==b&&a.busy())return a.pushQueue({scope:a,callback:a.back,args:arguments,queue:b}),!1;a.busy(!0);a.doubleCheck(function(){a.back(!1)});
t.go(-1);return!0};a.forward=function(b){if(!1!==b&&a.busy())return a.pushQueue({scope:a,callback:a.forward,args:arguments,queue:b}),!1;a.busy(!0);a.doubleCheck(function(){a.forward(!1)});t.go(1);return!0};a.go=function(b,c){var d;if(0<b)for(d=1;d<=b;++d)a.forward(c);else if(0>b)for(d=-1;d>=b;--d)a.back(c);else throw Error("History.go: History.go requires a positive or negative integer passed.");return a};a.emulated.pushState?(s=function(){},a.pushState=a.pushState||s,a.replaceState=a.replaceState||
s):(a.onPopState=function(b,c){var e=!1,e=!1,g;g=!1;a.doubleCheckComplete();if(e=a.getHash())return(g=a.extractState(e||a.getLocationHref(),!0))?a.replaceState(g.data,g.title,g.url,!1):(a.Adapter.trigger(d,"anchorchange"),a.busy(!1)),a.expectedStateId=!1;(e=a.Adapter.extractEventData("state",b,c)||!1)?(e=a.getStateById(e),g=!0):e=a.expectedStateId?a.getStateById(a.expectedStateId):a.extractState(a.getLocationHref());e||(e=a.createStateObject(null,null,a.getLocationHref()));a.expectedStateId=!1;if(a.isLastSavedState(e))return a.busy(!1),
!1;e.internal=g;a.storeState(e);a.saveState(e);a.setTitle(e);a.Adapter.trigger(d,"statechange");a.busy(!1);return!0},a.Adapter.bind(d,"popstate",a.onPopState),a.pushState=function(b,c,e,g){if(a.getHashByUrl(e)&&a.emulated.pushState)throw Error("History.js does not support states with fragement-identifiers (hashes/anchors).");if(!1!==g&&a.busy())return a.pushQueue({scope:a,callback:a.pushState,args:arguments,queue:g}),!1;a.busy(!0);var h=a.createStateObject(b,c,e);a.isLastSavedState(h)?a.busy(!1):
(a.storeState(h),a.expectedStateId=h.id,t.pushState(h.id,h.title,h.url),a.Adapter.trigger(d,"popstate"));return!0},a.replaceState=function(b,c,e,g){if(a.getHashByUrl(e)&&a.emulated.pushState)throw Error("History.js does not support states with fragement-identifiers (hashes/anchors).");if(!1!==g&&a.busy())return a.pushQueue({scope:a,callback:a.replaceState,args:arguments,queue:g}),!1;a.busy(!0);var h=a.createStateObject(b,c,e);a.isLastSavedState(h)?a.busy(!1):(a.storeState(h),a.expectedStateId=h.id,
t.replaceState(h.id,h.title,h.url),a.Adapter.trigger(d,"popstate"));return!0});if(c)try{a.store=q.parse(c.getItem("History.store"))||{}}catch(r){a.store={}}else a.store={};a.normalizeStore();a.Adapter.bind(d,"unload",a.clearAllIntervals);a.saveState(a.storeState(a.extractState(a.getLocationHref(),!0)));c&&(a.onUnload=function(){var b,d;try{b=q.parse(c.getItem("History.store"))||{}}catch(e){b={}}b.idToState=b.idToState||{};b.urlToId=b.urlToId||{};b.stateToId=b.stateToId||{};for(d in a.idToState)a.idToState.hasOwnProperty(d)&&
(b.idToState[d]=a.idToState[d]);for(d in a.urlToId)a.urlToId.hasOwnProperty(d)&&(b.urlToId[d]=a.urlToId[d]);for(d in a.stateToId)a.stateToId.hasOwnProperty(d)&&(b.stateToId[d]=a.stateToId[d]);a.store=b;a.normalizeStore();b=q.stringify(b);try{c.setItem("History.store",b)}catch(g){if(g.code===DOMException.QUOTA_EXCEEDED_ERR)c.length&&(c.removeItem("History.store"),c.setItem("History.store",b));else throw g;}},a.intervalList.push(k(a.onUnload,a.options.storeInterval)),a.Adapter.bind(d,"beforeunload",
a.onUnload),a.Adapter.bind(d,"unload",a.onUnload));if(!a.emulated.pushState&&(a.bugs.safariPoll&&a.intervalList.push(k(a.safariStatePoll,a.options.safariPollInterval)),"Apple Computer, Inc."===b.vendor||"Mozilla"===(b.appCodeName||""))&&(a.Adapter.bind(d,"hashchange",function(){a.Adapter.trigger(d,"popstate")}),a.getHash()))a.Adapter.onDomLoad(function(){a.Adapter.trigger(d,"hashchange")})};a.options&&a.options.delayInit||a.init()})(window);